#!/usr/bin/env python3
"""Feature checks that read the code, not the commit history. Stdlib only. See README.md.

  features.py inventory [--upstream REF]   classify every feature surface against the baseline tree
  features.py verify                       check features.tsv claims (and ledger consistency) against the working tree
"""
import hashlib, os, re, subprocess, sys

os.chdir(subprocess.run(["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True).stdout.strip())
DIR = os.environ.get("UPSTREAM_DIR", ".claude/upstream")
SCHEMA = "libraries/nestjs-libraries/src/database/prisma/schema.prisma"

# (label, directory, file regex). Prisma models are handled separately.
SURFACES = [
    ("Social providers", "libraries/nestjs-libraries/src/integrations/social", r"\.provider\.ts$"),
    ("Orchestrator workflows", "apps/orchestrator/src/workflows", r"\.ts$"),
    ("Orchestrator activities", "apps/orchestrator/src/activities", r"\.ts$"),
    ("Backend controllers", "apps/backend/src", r"\.controller\.ts$"),
    ("Backend auth and guards", "apps/backend/src/services/auth", r"\.ts$"),
    ("Agent, MCP and chat tools", "libraries/nestjs-libraries/src/chat", r"\.tsx?$"),
    ("Payment providers", "libraries/nestjs-libraries/src/services/payment", r"\.ts$"),
    ("Pricing and subscriptions", "libraries/nestjs-libraries/src/database/prisma/subscriptions", r"\.ts$"),
    ("Newsletter providers", "libraries/nestjs-libraries/src/newsletter", r"\.ts$"),
    ("AI video", "libraries/nestjs-libraries/src/videos", r"\.ts$"),
    ("Upload and storage", "libraries/nestjs-libraries/src/upload", r"\.ts$"),
    ("Frontend pages", "apps/frontend/src/app", r"page\.tsx$"),
    ("Frontend provider UIs", "apps/frontend/src/components/new-launch/providers", r"\.tsx$"),
    ("Frontend components", "apps/frontend/src/components", r"\.tsx$"),
    ("CI workflows", ".github/workflows", r"\.ya?ml$"),
]

def git(*a, check=True):
    r = subprocess.run(["git", *a], capture_output=True, text=True)
    if check and r.returncode:
        sys.exit("git %s failed: %s" % (" ".join(a), r.stderr.strip()))
    return r.stdout

def resolves(ref):
    return subprocess.run(["git", "rev-parse", "--verify", "-q", ref + "^{commit}"], capture_output=True).returncode == 0

def baseline():
    env = {}
    for line in open(os.path.join(DIR, "baseline.env")):
        m = re.match(r'^([A-Z_]+)=(.*)$', line.strip())
        if m:
            env[m.group(1)] = m.group(2).strip('"')
    return env

def blobs(ref, d, rx):
    out = {}
    for line in git("ls-tree", "-r", ref, "--", d, check=False).splitlines():
        meta, path = line.split("\t", 1)
        if re.search(rx, path):
            out[path] = meta.split()[2]
    return out

def models(ref):
    txt = git("show", "%s:%s" % (ref, SCHEMA), check=False)
    out = {}
    for m in re.finditer(r"^model (\w+) \{(.*?)^\}", txt, re.S | re.M):
        out[m.group(1)] = hashlib.md5(m.group(2).encode()).hexdigest()
    return out

def classify(b, h, u):
    rows = []
    for p in sorted(set(b) | set(h) | set(u or {})):
        inb, inh, inu = p in b, p in h, u is not None and p in u
        flags = []
        if inb and inh:
            flags.append("U" if b[p] == h[p] else "M")
        elif inh:
            flags.append("O")
        elif inb:
            flags.append("R")
        if u is not None:
            if inu and inb and u[p] != b[p]:
                flags.append("N")      # upstream changed this file since the baseline
            if inu and not inb and not inh:
                flags.append("X")      # new upstream file we do not have
            if inb and not inu:
                flags.append("D")      # upstream deleted it
        if flags:
            rows.append((p, flags))
    return rows

def inventory(upstream_ref):
    env = baseline()
    base, head = env["BASE_SHA"], "HEAD"
    if not resolves(base):
        sys.exit("baseline commit not in this clone")
    up = upstream_ref if upstream_ref and resolves(upstream_ref) else None
    print("# Feature inventory (generated by `features.py inventory`; do not edit by hand)\n")
    print("Compares **trees**, not commits. Baseline `%s` (%s) vs this checkout `%s`%s.\n" % (
        base[:8], env.get("BASE_DATE", "?"), git("rev-parse", "--short=8", "HEAD").strip(),
        (" vs upstream `%s`" % git("rev-parse", "--short=8", up).strip()) if up else ", upstream not fetched (run `sync-status.sh fetch`)"))
    print("Flags: **U** same as upstream baseline, **M** we modified it, **O** ours only, **R** we removed it"
          + (", **N** upstream changed it since the baseline, **X** new upstream file we lack, **D** upstream deleted it" if up else "") + ".\n")
    for label, d, rx in SURFACES:
        b, h = blobs(base, d, rx), blobs(head, d, rx)
        u = blobs(up, d, rx) if up else None
        rows = classify(b, h, u)
        counts = {}
        for _, fl in rows:
            for f in fl:
                counts[f] = counts.get(f, 0) + 1
        summary = ", ".join("%s %d" % (k, counts[k]) for k in "UMORNXD" if k in counts)
        print("## %s\n\n`%s` : %s\n" % (label, d, summary or "nothing"))
        for p, fl in rows:
            if fl != ["U"]:
                print("- [%s] `%s`" % (" ".join(fl), p[len(d) + 1:] if p.startswith(d + "/") else p))
        print()
    bm, hm = models(base), models(head)
    um = models(up) if up else None
    print("## Prisma models\n\n`%s`\n" % SCHEMA)
    for name in sorted(set(bm) | set(hm) | set(um or {})):
        fl = []
        if name in bm and name in hm:
            fl.append("U" if bm[name] == hm[name] else "M")
        elif name in hm:
            fl.append("O")
        elif name in bm:
            fl.append("R")
        if um is not None:
            if name in um and name in bm and um[name] != bm[name]:
                fl.append("N")
            if name in um and name not in bm and name not in hm:
                fl.append("X")
        if fl and fl != ["U"]:
            print("- [%s] `%s`" % (" ".join(fl), name))
    print("\n(models flagged U are unchanged and omitted; %d models in this checkout)" % len(hm))

def grep(pattern, path):
    r = subprocess.run(["git", "grep", "-qiE", pattern, "--", path, ":!.claude", ":!pnpm-lock.yaml", ":!*/locales/*"], capture_output=True)
    return r.returncode == 0

def exists(path):
    return subprocess.run(["git", "cat-file", "-e", "HEAD:" + path], capture_output=True).returncode == 0

def verify():
    rows = [l.rstrip("\n").split("\t") for l in open(os.path.join(DIR, "features.tsv"))][1:]
    ledger = [l.rstrip("\n").split("\t") for l in open(os.path.join(DIR, "ledger.tsv"))][1:]
    fails = warns = 0
    for r in rows:
        if len(r) != 6:
            print("BAD ROW  %r" % r[0]); fails += 1; continue
        name, lkey, origin, expect, check, notes = r
        path, _, rx = check.partition("::")
        present = (exists(path) if not rx else grep(rx, path)) if (exists(path) or rx) else False
        ok = present if expect == "present" else not present
        if ok:
            print("ok       %-28s %-9s %s %s" % (name, origin, expect, check))
        elif notes.startswith("KNOWN GAP"):
            print("WARN     %-28s %-9s expected %s but %s  <- %s" % (name, origin, expect, "found" if present else "missing", notes)); warns += 1
        else:
            print("FAIL     %-28s %-9s expected %s but %s: %s" % (name, origin, expect, "found" if present else "missing", check)); fails += 1
    covered = {r[1] for r in rows if len(r) == 6 and r[1]}
    for l in ledger:
        if l[0].startswith("feature:") and l[0] not in covered:
            print("FAIL     ledger row %s has no code check in features.tsv" % l[0]); fails += 1
    print("\n%d failed, %d known gaps" % (fails, warns))
    return 1 if fails else 0

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "inventory":
        ref = sys.argv[sys.argv.index("--upstream") + 1] if "--upstream" in sys.argv else os.environ.get("UPSTREAM_REF", "upstream/main")
        inventory(ref)
    elif cmd == "verify":
        sys.exit(verify())
    else:
        print(__doc__); sys.exit(2)
